### ISSUE TITLE
NullPointerException when using AppCompatActivity with appcompat-v7:23.1.0 

### ISSUE THREAD

**Issue by Piasy** [yshrsmz/KeyboardVisibilityEvent#5] opened 2015-11-07 07:40 UTC
My activity is AppCompatActivity, and when I use appcompat-v7:22.2.1, `activity.findViewById(android.R.id.content)` 
returns 
`android.widget.FrameLayout{1a8e3406 V.E..... ......I. 0,0-0,0 #1020002 android:id/content}`
which works well.
But when I use appcompat-v7:23.1.0, `activity.findViewById(android.R.id.content)` returns:
`android.support.v7.internal.widget.ContentFrameLayout{8337fad V.E..... ......I. 0,0-0,0 #1020002 android:id/content}`
whose children are all null, causing the NPE.

**Comment by yshrsmz** [comment] 2015-11-07 08:09
Thank you for reporting, I'll look into it.

**Comment by yshrsmz** [comment] 2015-11-07 09:54
hmm...
I cannot reproduce the issue.
Could you provide a sample project which reproduce the problem?

**Comment by Piasy** [comment] 2015-11-07 12:57
Sorry that I can't create a sample project that will reproduce it, but I do face it in our production APP project. I'll keep trying, and will provide the sample project when it's ready.

**Comment by yshrsmz** [comment] 2015-11-07 13:06
Thanks!
For the meantime, I've just updated the sample project with AppCompat v23.1.0.
You can try it to see if it cause the problem :)

**Comment by yshrsmz** [comment] 2015-12-15 07:24
closing for now

**Closed by yshrsmz** 2015-12-15 07:24 UTC
